version: "3"

services:
  vban_send:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./vban_send.py:/app/vban_send.py
      - ./config.ini:/app/config.ini
    network_mode: host
    restart: unless-stopped
    logging:
      driver: json-file
      options:
        max-size: "5m"
        max-file: "2"